all:
		#$(MAKE) -C serial_example
	    $(MAKE) -C parallel_code	
		#$(MAKE) -C serial_code

clean:
		#$(MAKE) -C serial_example clean
		$(MAKE) -C parallel_code clean
		$(MAKE) -C serial_code clean
		$(MAKE) -C simple-jpeg clean
	
